### ISSUE TITLE
Bug: sometimes two empty lines between dd and dt

### ISSUE THREAD

**Issue by waldekmastykarz** [StfBauer/markshell#23]
In some cases, markshell renders two empty lines between dd and dt:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/11164679/98027933-ae24fd80-1e0d-11eb-8a7c-2c4732d7d194.png">

Notice the spacing between `help` and `authType`.

The source md is: https://github.com/pnp/cli-microsoft365/blob/ae22962532be27ab268823113ef2dbd2fda93669/docs/docs/cmd/login.md which doesn't have this spacing

I noticed this bug in 1.3.0 but it's still there in 1.3.2.

**Comment by StfBauer** [comment]
is this happening on Windows or MacOS?

**Comment by waldekmastykarz** [comment]
I noticed it on macOS. Haven't verified on Windows

**Comment by StfBauer** [comment]
1.3.3 should work now.

**Comment by waldekmastykarz** [comment]
Brilliant! Will check it out asap! Thank you so much!

**Comment by waldekmastykarz** [comment]
Just checked 1.3.3 and it seems like it doesn't quite fix the issue and it introduces a regression as well:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/11164679/99710076-673b3700-2aa0-11eb-8e1f-7338a8ef5f63.png">

Notice the doubled spacing being still there but also `..` leading `dd` lines. Tested using https://github.com/waldekmastykarz/cli-microsoft365/blob/2b60f188134ef99b22b62886113799dae26bfcc7/docs/docs/cmd/spo/site/site-list.md

**Comment by StfBauer** [comment]
Well, the .. are not from my side. Can you post the configuration in here too?

**Comment by StfBauer** [comment]
Test result of 1.3.3 of the previous result:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/5503835/99740896-2b1fca80-2ad0-11eb-9c08-6dc65ae304af.png">

I update to 1.3.4 with some minor tweaks in the code. might help you in your case. TBO, I am not sure who adds the ... upfront, it is not me.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/5503835/99742223-5952d980-2ad3-11eb-9528-c3b0cd26c3f4.png">

**Comment by waldekmastykarz** [comment]
Hmm, let me double check

**Comment by waldekmastykarz** [comment]
Aren't the dots coming from here? https://github.com/StfBauer/markshell/blob/6061e6691d02382a545f65be793d3856fe80472b/lib/index.js#L601

**Comment by StfBauer** [comment]
Yeah 🤦‍♂️ left indent = set to 0 in my test..... Well, then we have a bigger problem than that.

**Comment by StfBauer** [comment]
Maybe now with 1.3.5 but is looks sometimes strange.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/5503835/99941844-fd0be600-2d6e-11eb-83fa-737e228d5e68.png">

**Comment by waldekmastykarz** [comment]
Looks good to me! I'll give it a try! Thank you! 👏

**Comment by waldekmastykarz** [comment]
After upgrading to 1.3.5 I'm getting some extra output:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/11164679/99999414-69630580-2dc0-11eb-8a6b-a31fe0a7edae.png">

It seems like the number is coming from here:

https://github.com/StfBauer/markshell/blob/d7157f7f1d9cd10f4a4a89fd0f09766437f33af0/lib/index.js#L591

The warning about circular reference is coming from:

```text
$ node --trace-warnings ./dist/index.js help spo site list
(node:84488) Warning: Accessing non-existent property '_theme' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object.<anonymous> (/Users/foo/cli-microsoft365/node_modules/markshell/lib/syntaxhighlighter/index.js:40:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.patchedRequire [as require] (/Users/foo/cli-microsoft365/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
```

The circular reference issue is returned only in Node@14. In Node@12 there's no error. I've switched to @14 recently since it's LTS now so it would be good to fix it to avoid issues if folks use Node@14.

**Comment by waldekmastykarz** [comment]
I noticed that the issue with the circular reference that's reported in Node@14 is present in markshell@1.3.0. As it's not related to this issue, we could track it separately if it's easier for you.

The bad news is, that the warning is being displayed all the time when using CLI on Node@14 so it would be very helpful if we could address it asap, so that folks can use CLI on Node@14 without any issues.

**Comment by StfBauer** [comment]
1.3.6 - Most likely fixed 🤦‍♂️ I hate code leftovers.

**Comment by waldekmastykarz** [comment]
The issue with double lines is fixed indeed! 💪 

What's left though:
- warning about circular reference in Node@14
- debug indent size being print: https://github.com/StfBauer/markshell/blob/613c1ac8922a2f1a7b17c228b33a79f34215b3b1/lib/index.js#L591

**Comment by waldekmastykarz** [comment]
All issues confirmed fixed in v1.3.7. ❤️
